default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: event_development
  username: wlapp_db_admin
  password: wlapp-db-pas
  host: localhost


test:
  <<: *default
  database: event_test
  username: wlapp_db_admin
  password: wlapp-db-pas
